#!/bin/bash
pri=$(xsel -o -p | tr '\n' ':' | sed -E 's/^\s+//')
echo "$pri" | head -1 | dzen2 -ta l -w 400 -p 2 -y -1 -fn "Monospace-10" -bg "#000020" -fg "#ffffff"&

buf=$(xsel -o -b | tr '\n' ':' | sed -E 's/^\s+//')
echo "$buf" | head -1 | dzen2 -ta l -w 400 -p 2 -x 400 -y -1 -fn "Monospace-10" -bg "#400000" -fg "#ffffff"&

if pgrep tmux; then
    buf=$(tmux show-buffer | tr '\n' ':' | sed -E 's/^\s+//')
    echo "$buf" | head -1 | dzen2 -ta l -w 400 -p 2 -x 800 -y -1 -fn "Monospace-10" -bg "#002000" -fg "#ffffff"&
fi
